apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/odysseia-greek/aiskhylos
    newTag: v0.2.2
  - name: ghcr.io/odysseia-greek/anaximenes
    newTag: v0.1.2
  - name: ghcr.io/odysseia-greek/eupalinos
    newTag: v0.3.1
  - name: ghcr.io/odysseia-greek/euripides
    newTag: v0.2.3
  - name: ghcr.io/odysseia-greek/polykleitos
    newTag: v0.0.1
  - name: ghcr.io/odysseia-greek/sophokles
    newTag: v0.3.2
