apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sophokles
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sophokles
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sophokles
        app.kubernetes.io/part-of: attike
    spec:
      serviceAccountName: sophokles
      tolerations:
        - operator: Exists
      containers:
        - name: sophokles
          image: ghcr.io/odysseia-greek/sophokles
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: sophokles
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NETWORK_OBSERVER_PROC_ROOT
              value: /host/proc
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
