apiVersion: v1
data:
    token: ENC[AES256_GCM,data:N2OuzBCnJWZ6kyIgr7qSW2Q3+Nue4N1FSdmoa9oU5QL8S0NusnBe0GeZ7y3RpGQ9eSzzvg9KcLPPDXcMmq0RnQUw6F+AmktD1OsXniY623PHu4NcceoN7Axbt3gx5lud1EzKQ2LtbYhupXYUUylB36Jp1+2/6kgbaVpREg==,iv:8qgoBb478n6M/Q5ptv6EmwpZN+EnYK8dQlWehhHWu1Y=,tag:ULHY64teTuqNU8skH0aP1A==,type:str]
kind: Secret
metadata:
    name: github-status-token
    namespace: tekton-pipelines
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T19:57:22Z"
    mac: ENC[AES256_GCM,data:Uf+MiPidi6SGmNuEshNjQQev/cdNjXmmQZ8DkpZSCvClD4X3z3h5w20c6yNn15tRSqYUx56Nlrjg1ZohV4TeHEsz8/ck494ejxVombUs5Juaej/4U4m6CHwevso52pSI3lmUgjivetxuGGX16rGWcGsTUAHeE5j/f+d6osHTtls=,iv:XpJ65vhnjM7tC82aiUvocCLLenJ5A7FABhO8rkwhMqM=,tag:JqlLZEomwMLOLsJZtMG7AA==,type:str]
    pgp:
        - created_at: "2026-06-04T19:57:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/dvIqia++XvAQ/+OcXgZqQ4uPMEfplQUvfna8BKtBDfvX+hdz0xiceyFGBq
            Z0Lwp02nXXMqokoQdcNpeD0+NQxJ8nlQYnVqRNz+yUFVlCmgWWCwIKN1hz/AXc49
            Qpzwfe062q1Jsx5aztXHBR+bV2o0boVAUygrL9XMexuHJoP3YQGkmH4TL5k5cWwh
            hXC8qm3m18r8EyKm+vuO2l81vClPnWKa6/uNvjX3qa1wxZjSoam70TF5NIKYoSzz
            chzgoQOBycUNo6ia7Y7bwLrzwLDoHdPbV6jQVQfNxnFOdfSdNKEbN4I+J6FoPQXx
            LYRCjzhzH7mJT37saDgLN8Wd+U/4zCfFarGzKnAuev5PoB0BMN38OXMI8QQ831Fg
            eUOfvOsL4yrMzaUpXWV0eLCok4H7yFHrROFhRtOrLH3EG9HTyY9CUggIkk26KvF6
            1JOLhbnBcZ6qAEFwa0IpDlpRHuyO2+jkzNTqejFB8TS2Kc8PhiodqDukddAFdTUl
            7TE+SFioK6CUvVlbkK6CzkBZglLg5J8jLausbPqZNKAzk9ilRIWdrePvM0TXrfZQ
            JCTutydy4hMERtV+Xen46ePJLsHfUCpgmNHvy/z1vnCxY6JGVXzszKSOinCaftca
            pHMbkJm/y455XH1UqFzRGkMTuaFcefXo0FLoHikF/Nt/LLIe5R25qEr11pHhn7HU
            aAEJAhCP3rIUSPrupTs3CfStX5ErsfIT9FG5gwgYh3pUB+uv3QJL4yRBJWXdU9Ev
            sUkEs7YywP2JpjqoZds0NLVh5OgzU+Rfc8GXDGbXeeROyEyGI8yV5pKAcnLy5zlq
            Ej38Hf2lmf0H
            =wdy+
            -----END PGP MESSAGE-----
          fp: 3C8B5BB6281C34C5E80C473086FCFB28CF0EC482
    version: 3.13.1
