apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - ../../../base/zot
  - ingressroute.yaml

patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: zot-data
    path: patch-pvc.yaml
