apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - ../../../base/zot
  - ir.yaml
  - mirror-base-images.yaml
  - secret.yaml

patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: zot-data
    path: patch-pvc.yaml
  - target:
      version: v1
      kind: Service
      name: zot
    path: patch-service.yaml
