apiVersion: v1
data:
    htpasswd: ENC[AES256_GCM,data:jO2bhgqBa4Il9kz3WTW6oyuk0COkMt35q3vOedY51CaNf1VoRXDKlNPyJCd7E2u6O7+nzxXUEQu5zIkCg/iANRHgngCzsTYwE+hhDnxsRMKHsgsGgf74fA==,iv:K6Ch6OdXEn4JDb9EwREaFQxd3kN3Y4DDzSWBcM3x2hQ=,tag:2JmgwBWBH7eOtXLUl81M2g==,type:str]
kind: Secret
metadata:
    name: zot-auth
    namespace: zot
sops:
    lastmodified: "2026-05-02T09:20:52Z"
    mac: ENC[AES256_GCM,data:j0Nw5vsu+KU3k9NDEPqnjD9EMRrwj6WKNNCFXC5cS/MpEM9vHfc0vO4aPIcw3IcrKmWjG86SecKlNUrCPwiQoAB9OMJ3ZMvopz+iL1CPNeAIjJLOeDphfhBwtp803Nt1TYzjqw36uJuvmMKZkNtbLs56Lxm35BMuFuoyyksRilc=,iv:XaE8O/Lx6rborCHqp/ReUvESs5EIEkyIs3+IUEFEKWo=,tag:00F2l5IFwWeD22XtFs9gDA==,type:str]
    pgp:
        - created_at: "2026-05-02T09:20:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/dvIqia++XvAQ//WTonB2DWzjBxmykNq1APkwRdjt7rn2rR4rMt+LsdKz6O
            dDsOFVBPzKFdMhrQEpCySvCmDhClJC5SjfuMOHCl+QN+xwgtBMvRif7ycrKDo0EA
            rtOfzXTc8SGj/B2fjAiftUnfgD75pswzEMKw/a/kqb9NhHMw1GYDJETT5QvxhJfe
            BpwZeqgWAeUyxCdGnlSJHoKxBjEDdXWk6c/wY9dLYmM+9B9Rdebjn0Y7vvqo4e0b
            98sMJHdGS5HYtRruR+3DDDe40Z4O4OZ+MwbJyhXJmKexpJ+5i5q90gP4IWSsiWBR
            tH/s+g3psd5bTqvRwzM4OKOBcBtOgct31cUV4kB4Mmvybi+iyBV9RvO6vx0T3YdN
            qL14pSysiz965hRZMhvMe867ur+1RNyz9mXUKvXHC5DqXPG0Jua8IhccN01c0QV2
            jE4i4Qcnnp0NXKlj2O4Opo5EhlfxDyWsJuqamRg8k+ilPv0L26t6Bbxy4jktIEUK
            1aL+fsTSkOIPeULiWSz1xTAW/v1wLmtGuJxRrgoGuQh/8YIf00yOlv1gB6I4t5zR
            nHVHHPSa+chznrcoRPf+5T3kA5jfG8nPSUmTP3SQye9Y9QS4PDFRAuVi0HzBZos7
            q5lSQxct7xlA5BFmMn8FKP1DKaRSL/xeTNeQ+/bA9tbJr1oEPQJ9kCAGDpeEhzjU
            aAEJAhCl3GOHgL2QotZDLkGCfZS1jhkt+zcJh3VQFNbtWFSnFULMPDu0bDnw9lll
            6YdtKI45z55G8LqhvunZ3wML/skznh/WzfNw4W49BasMri+wZ3W/lpLMLT6pca2L
            vWYSc50o4Vc8
            =2tPj
            -----END PGP MESSAGE-----
          fp: 3C8B5BB6281C34C5E80C473086FCFB28CF0EC482
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
