---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: themistokles
  path: themistokles/ge/overlays/hellas/cloudflare-tunnel
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
