apiVersion: v1
data:
    tunnel-token: ENC[AES256_GCM,data:t7yDK82IDoY2U/Xr3m/PxNWm+elM0uKloeAGoPqyVhZqpwCGx6Cq87qmcPDehxff7HtpZvr8YpQZBB+AEeWjUWWQZfeiIcZdW0iP48ixpk9NSRbyZcwFlqqYYLGHsxO8QJMDK/vAhg2lMl6RzxVHl1t7fkR/3xz6n41GJWT1v2glgXy98qupJYDuCFDSGJWFu0f4aVwIPh8Z0Mj9I/bSc845R68gyyVtDj386k6ek5D1LWeRwPNXhibqyFEXw+N8kXOPjdQ0syQB969myn7tt88cXSPx4N36OgZwTiqmT8bLPAv/nsqc5hFf1fdcc4wqeeKgB7H0qFA=,iv:33ILWSc7/2JrsUluIrs8tTBMR7wu8phVRs/+gWJcRlo=,tag:X97d7KYJNEq0RjvkMyRULA==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare-tunnel
sops:
    lastmodified: "2026-03-28T11:20:36Z"
    mac: ENC[AES256_GCM,data:KDHThhJVHja7NJKU1rPCscJHLwEOHL4l3RwE8faTIzKlDtlZdSL0FoUcRMMejwV2dXpkzoOiVUn3QnHqByVZALZb2FyWYedPc+BkURl4rSQRR/FmPMi+RZTbF4eCgHbeOon1nThEMD6NB5FR4qmhsgppPip9+I9zrXjg13AsLLg=,iv:G0pkQpx3Yn1csvU1jCXDlEPjUn096LoqXGNzNrPIRZQ=,tag:gDZs/c25zzrPRMqihPzVlw==,type:str]
    pgp:
        - created_at: "2026-03-28T11:20:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/dvIqia++XvAQ//ZYiacPLEw0x8nWFRim7Dz6uVuMprvf+s6GdZ+tDU4ySp
            GrD1A8nWO8RtDKZD+141WhN0vqGnMPm2QbV7l5Q2gXq3UTUpb2Xd2qmELNtbO64V
            YITR3usAbDhKkKGkxSK8Bf7Ugf5JaZ3226R8YlE4KOJr3xws0DotAZjwWfRFUw2f
            QC9wo4HwGDrkkx8LvYCdt0MFBvIKpEVla3EO3PuG2KhxP0zw+ukp9u3VDb1Jvp2S
            0Q//qZm+htBoelBP+qSPdvxYIRo1X5ZZS1+GkuenE+I6qpNNrjdP/yNCy9X9VE/a
            TdXFBgHxRtJAxVDiVVQTGKYz+vOtqgZPq9Fxe7g7UIqojfgpfPMp42jIpiOQn558
            oHAoVBNPoBgCj9aw/ojUI0J6EGLBJTBh8eo4AxO1Ys9aO1OwIctyzA7MaUFkFKuD
            dMb/cSdo6OUdF9Jx99qTxQ0JBl/XUFueAAziZb+CdyAcPum6bNToUf6Ik1wVhc5B
            NpBczWz9wkkoVtzoLNUMkYuebetSM7Th7MRzRhjg9QkWkFpSJ6x7Jppch5dGFbQE
            On1X7cKFXDn7/1175dQ4Fi8G5cEyEMlKdUwQimp502kOtOEeh/oFR9IyEXU8D5kh
            rGVGKAjmkhbnka2s6MpGBhzYOlTpYt7kEUPRNuDKlAh9sXPrDWhqaorX9jI5DcLU
            aAEJAhCF8e3wffkTDW/v0C9WSn8yYZY2IsHnLg7QfLJCyzgn8mIS2P2U3lIy2niR
            sKwUS9JuDvScYKyIvbNFRu2Cn/B/brkWTWjDehBhHGRBG27zI9imtoftPtqzl8YU
            ox/ZZziaAUa7
            =a5JR
            -----END PGP MESSAGE-----
          fp: 3C8B5BB6281C34C5E80C473086FCFB28CF0EC482
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
