apiVersion: v1
data:
    tunnel-token: ENC[AES256_GCM,data:O4HMQhviyCNxWCT7jW+ncA==,iv:hhhwGOkZg4R9j4oGoJS7+A3UZKPp6Irt1fgcOKVce4M=,tag:2ipLZOBaOiYn/TcpQl3Dug==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare-tunnel
sops:
    lastmodified: "2026-03-28T11:03:13Z"
    mac: ENC[AES256_GCM,data:woRzoXQhCc92ufD54QihGWx2ZbD+3m0RgqR5OBu7gLozh7/A/81fg+zpqAwUZEP8CSXr5b5v7YTKOt4dIFW+AxVdd+Qmso2emfIdtjDQCiSG82GUaP2pV0NvSgoEZZTFI/BUjDOVDHXcYQZVCbh/ijVaLhZVOzl8Zq2klI6ITAM=,iv:5aBW05bg703iQrv/45h0f2ewRypcMin28iqZP2NhUXY=,tag:FtxwPb1YDN0XiEG+zGF0aA==,type:str]
    pgp:
        - created_at: "2026-03-28T11:03:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/dvIqia++XvARAAipitrZ6RL9f2ChKikqZAZTie+R62/N9vjIf1CgnBN2gC
            Z8Aa+3inrQz7Ei/8tVz91XtAjJrONAT++yO+HMmJMoSj6q4vchMEUFjkObmwoxej
            NiXuJ4Zux7rgQ5AkVjXGKkdMg6ZCxiMc61qsCDNoVzX/6xpKDU8/1Aa6xI8PAJl9
            hzIvJRWrPcGFbYYsbMFDYxubzVfE5rlW0bioDTLXL1u79EMAQ6yYphkM3Gm0YBqQ
            CFaD64h7PY+1tjyHg4xxDBPHuyglEE3Mfxxe6RYrpCSf5bb4JfoQ9QjYqboamdMd
            /tNf1qjGvQ9m9+mmZzq2TOgX4cjiX3oQtEQ9BeGJX3oBSHeIvwv6i855wj2J3kB1
            0TK5ADz3px1q9S4+FP2F7V5e06z+IE0KacJm6zZzFJa41JBUVu+cMLS8Ssmcf0vk
            kqEL5tjLWZDYGAHYir321dILFy5Gi2sYRU7bIc5srbUlj7guc+s8MCD5rtmNAPgm
            fDN2qDwR4sSbvElztICG9giLnw8IiNUgCPD/a29VH474V/9KcAX6ncpXj2S2Q1Cp
            W9pRleXP9FgmlVS93xRlU2Lwfwuz8NXqdl3Zewu22Je8Ytere64pP9wZ85NnYkcR
            lBREZb/uYX1ZqicAhw5t70D/0hbxajz2zU2jEmNpV83zeDXida4DGPXWviFvZGPU
            aAEJAhClXZLNIT+Hm00xfUBxvCUgzoDnaip78GHxP9xpaG8LSWymav8uNbs4oQPQ
            6Uj4HSzl0aqsbY0o0jXdtmeeN8723bsuv2a+MaGmYDLz/DWAu4MIEItrXj1n/u4c
            wmhk3te2dlGV
            =7Ymr
            -----END PGP MESSAGE-----
          fp: 3C8B5BB6281C34C5E80C473086FCFB28CF0EC482
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
