apiVersion: apps/v1
kind: Deployment
metadata:
  name: perikles
  labels:
    app: perikles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perikles
  template:
    metadata:
      labels:
        app: perikles
        release: perikles
    spec:
      serviceAccountName: periklessa
      nodeSelector:
        kubernetes.io/hostname: korinthos-hellas
      containers:
        - name: perikles
          image: ghcr.io/odysseia-greek/perikles
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: perikles
            - configMapRef:
                name: elastic-roles-and-cnp
          ports:
            - name: dashboard
              containerPort: 8080
          env:
            - name: CRD_NAME
              value: perikles-mapping
            - name: L7_MODE
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
