apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olympia

resources:
  - deployment.yaml
  - service.yaml
  - ir.yaml

components:
  - ../../../../../pyr/koinos/deployment/aristophanes
  - ../../../../../pyr/koinos/common-env/base/deploy
