apiVersion: v1
kind: Service
metadata:
  name: hypatia
spec:
  selector:
    app: hypatia
  ports:
    - name: grpc
      port: 50061
      targetPort: grpc
    - name: http
      port: 8080
      targetPort: http
