package command

const (
	DefaultKubeConfig         = "/.kube/config"
	DefaultNamespace          = "odysseia"
	DefaultHelmChartName      = "themistokles"
	DefaultMykenai            = "mykenai"
	DefaultSecretName         = "elastic-root-secret"
	DefaultPerikles           = "perikles"
	DefaultPeriklesSecretName = "perikles-certs"
	ConfigFilePath            = ".odysseia"
	NginxRepoPath             = "https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.0.19/ingress-nginx-4.0.19.tgz"
	NginxNamespace            = "ingress-nginx"
	DefaultVaultServiceName   = "vault"
	DefaultExamplePath        = "go/src/github.com/odysseia-greek"
	SettingsName              = "odysseia.yaml"
	GitPath                   = "https://github.com/odysseia-greek"
	Olympia                   = "olympia"
	Delphi                    = "delphi"
	Agora                     = "agora"
	Attike                    = "attike"
	Aristophanes              = "aristophanes"
	Ploutarchos               = "ploutarchos"
	Docs                      = "docs"
	DefaultAppProfile         = "full"
	ElasticOperatorName       = "aristoteles"
	DefaultImageFile          = "images.yaml"
	HelmValuesFile            = "values.yaml"
	HelmChartFile             = "Chart.yaml"
	OdysseiaImageRepo         = "ghcr.io/odysseia-greek/"
	DefaultProfile            = "k3s"
	DefaultEnv                = "prod"
)
