package command

const (
	DefaultKubeConfig           = "/.kube/config"
	DefaultNamespace            = "odysseia"
	DefaultHelmChartName        = "themistokles"
	DefaultMykenai              = "mykenai"
	DefaultAdmin                = "admin"
	DefaultSecretName           = "elastic-root-secret"
	DefaultDockerRegistrySecret = "harbor-images"
	DefaultHarbor               = "core.harbor.domain"
	DefaultHarborUrl            = "https://core.harbor.domain:30003/"
	DefaultHarborCertSecretName = "harbor-certs"
	DefaultPerikles             = "perikles"
	DefaultPeriklesSecretName   = "perikles-certs"
	ConfigFilePath              = ".odysseia"
	NginxRepoPath               = "https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.0.19/ingress-nginx-4.0.19.tgz"
	NginxNamespace              = "ingress-nginx"
	QueueName                   = "queue"
	DefaultVaultServiceName     = "vault"
	DefaultProjectName          = "odysseia-greek"
	DefaultExamplePath          = "go/src/github.com/odysseia-greek"
	SettingsName                = "odysseia.yaml"
	GitPath                     = "https://github.com/odysseia-greek"
	Olympos                     = "olympos"
	Delphi                      = "delphi"
	Attike                      = "attike"
	Aristophanes                = "aristophanes"
	Ploutarchos                 = "ploutarchos"
	Docs                        = "docs"
	DefaultAppProfile           = "full"
	ElasticOperatorName         = "aristoteles"
	DefaultImageFile            = "images.yaml"
	HelmValuesFile              = "values.yaml"
	HelmChartFile               = "Chart.yaml"
	OdysseiaImageRepo           = "ghcr.io/odysseia-greek/"
	DefaultProfile              = "k3s"
	DefaultEnv                  = "prod"
)
