apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  values:
    cephBlockPools:
      - name: pyxis
        spec:
          failureDomain: host
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: pyxis
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: WaitForFirstConsumer
      - name: kibotos
        spec:
          failureDomain: host
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: kibotos
          isDefault: false
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          volumeBindingMode: WaitForFirstConsumer
    cephClusterSpec:
      placement:
        all:
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
      storage:
        # Keep OSDs off the 4GB antioch node and only consume the dedicated external SSD.
        deviceFilter: "^sda$"
        nodes:
          - name: pella-hellenistike
          - name: alexandreia-hellenistike
