apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  values:
    cephBlockPools:
      - name: pyxis
        spec:
          failureDomain: host
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: pyxis
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: WaitForFirstConsumer
      - name: kibotos
        spec:
          failureDomain: host
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: kibotos
          isDefault: false
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          volumeBindingMode: WaitForFirstConsumer
    cephClusterSpec:
      cephConfig:
        global:
          osd_pool_default_size: "2"
          mon_warn_on_pool_no_redundancy: "false"
      mon:
        count: 3
        allowMultiplePerNode: true
      mgr:
        count: 1
        allowMultiplePerNode: true
      logCollector:
        enabled: false
      resources:
        mon:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 128Mi
        mgr:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
        osd:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        prepareosd:
          requests:
            cpu: 50m
            memory: 50Mi
      placement:
        all:
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
      storage:
        # Start with the smallest useful Ceph profile: all three SSDs, one replica.
        deviceFilter: "^sda$"
        nodes:
          - name: pella-hellenistike
          - name: antioch-hellenistike
          - name: alexandreia-hellenistike
