apiVersion: v1
data:
  ERATOSTHENES_SERVICE: eratosthenes.alexandreia.svc.cluster.local:50060
  KALLIMACHOS_SERVICE: kallimachos.alexandreia.svc.cluster.local:50060
kind: ConfigMap
metadata:
  name: dionysios
  namespace: alexandreia
---
apiVersion: v1
kind: Service
metadata:
  name: dionysios
  namespace: alexandreia
spec:
  ports:
  - name: http
    port: 5000
    targetPort: http
  - name: grpc
    port: 50060
    targetPort: grpc
  selector:
    app: dionysios
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    volumes.odysseia.io/secrets: "true"
  labels:
    app: dionysios
  name: dionysios
  namespace: alexandreia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dionysios
  template:
    metadata:
      annotations:
        odysseia-greek/access: grammar
        odysseia-greek/role: api
        perikles/accesses: solon;eratosthenes;aristarchos;kallimachos
      labels:
        app: dionysios
        release: dionysios
        version: v0.2.4
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        envFrom:
        - configMapRef:
            name: dionysios
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/dionysios:v0.2.4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 20
          periodSeconds: 20
        name: dionysios
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 50060
          name: grpc
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 1
          periodSeconds: 20
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts: []
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/aristophanes:v0.7.2
        imagePullPolicy: Always
        name: aristophanes
        ports:
        - containerPort: 50052
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 32Mi
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/aristides:v0.0.4
        imagePullPolicy: Always
        name: aristides
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /app/config/vault
          name: vault-server-tls
          readOnly: true
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      initContainers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTIC_ROLE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/role']
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/periandros:v0.1.5
        imagePullPolicy: Always
        name: periandros
        volumeMounts:
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      volumes:
      - name: solon-certs
        secret:
          secretName: solon-tls-certs
      - name: vault-server-tls
        secret:
          secretName: vault-server-tls
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dionysios
  namespace: alexandreia
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 30
        type: Pods
        value: 2
      stabilizationWindowSeconds: 120
    scaleUp:
      policies:
      - periodSeconds: 10
        type: Pods
        value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 40
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dionysios
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    volumes.odysseia.io/secrets: "true"
  labels:
    app: anaximander
  name: anaximander
  namespace: alexandreia
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        odysseia-greek/access: grammar
        odysseia-greek/role: seeder
        perikles/accesses: solon
      labels:
        app: anaximander
        release: herodotos
        version: v0.2.0
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        envFrom:
        - configMapRef:
            name: dionysios
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/anaximander:v0.2.1
        imagePullPolicy: Always
        name: anaximander
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/aristides:v0.0.4
        imagePullPolicy: Always
        name: aristides
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /app/config/vault
          name: vault-server-tls
          readOnly: true
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      initContainers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTIC_ROLE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/role']
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/periandros:v0.1.5
        imagePullPolicy: Always
        name: periandros
        volumeMounts:
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: solon-certs
        secret:
          secretName: solon-tls-certs
      - name: vault-server-tls
        secret:
          secretName: vault-server-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dionysios-route
  namespace: alexandreia
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`hellas.odysseia-greek`) && PathPrefix(`/dionysios/v1`)
    services:
    - name: dionysios
      port: 5000
