apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  values:
    nodeSelector:
      odysseia-greek/ingress-role: primary
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    service:
      enabled: true
      type: NodePort
    ports:
      web:
        nodePort: 30080
      websecure:
        nodePort: 30443
