apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - alexandros
  - antigonos
  - dareios
  - demokritos
  - eukleides
  - hefaistion
  - parmenion
  - perdikkas
  - ptolemaios
