---
- name: Bootstrap Hellenistike Raspberry Pis
  ansible.builtin.import_playbook: bootstrap-hellenistike.yaml

- name: Install k0s on Hellenistike
  ansible.builtin.import_playbook: k0s-cluster.yaml
  vars:
    k0s_controller_group: poleis-hellenistike-controller
    k0s_worker_group: poleis-hellenistike-workers
    k0s_all_group: poleis
    k0s_expected_node_count: 3
