apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoukydides
  labels:
    app: thoukydides
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thoukydides
  template:
    metadata:
      labels:
        app: thoukydides
        release: thoukydides
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: reading
        perikles/accesses: "solon"
    spec:
      containers:
        - name: thoukydides
          image: ghcr.io/odysseia-greek/thoukydides
          imagePullPolicy: Always
          env:
            - name: PORT
              value: ":50060"
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom: []
          volumeMounts: []
          ports:
            - containerPort: 50060
      volumes: []
