apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ionia
  - herodotos
  - diodoros
  - thoukydides
  - herakleitos
  - hekataios
  - ../../../base/ionia/artafernes

components:
  - ../../../base/ionia/stoicheia/images
  - ../../../base/ionia/stoicheia/version

labels:
  - pairs:
      environment: "romaioi"
      variant: "k0s"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true
