apiVersion: batch/v1
kind: Job
metadata:
  name: hekataios
  labels:
    app: hekataios
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  template:
    metadata:
      labels:
        app: hekataios
        release: hekataios
      annotations:
        odysseia-greek/role: seeder
        odysseia-greek/access: reading
        perikles/accesses: solon
    spec:
      containers:
        - name: hekataios
          image: ghcr.io/odysseia-greek/hekataios
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom: []
      restartPolicy: Never
      volumes: []
  backoffLimit: 3
