apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  openbao.hcl: |
    disable_mlock = true
    ui            = false
    api_addr      = "https://vault.delphi.svc:8200"
    cluster_addr  = "https://vault.delphi.svc:8201"

    listener "tcp" {
      address             = "[::]:8200"
      cluster_address     = "[::]:8201"
      tls_cert_file       = "/vault/userconfig/vault-server-tls/tls.crt"
      tls_key_file        = "/vault/userconfig/vault-server-tls/tls.key"
      tls_client_ca_file  = "/vault/userconfig/vault-server-tls/ca.crt"
    }

    storage "file" {
      path = "/vault/data"
    }
