apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
data:
  openbao.hcl: |
    ui            = true
    api_addr      = "https://openbao.delphi.svc.cluster.local:8200"
    cluster_addr  = "https://openbao.delphi.svc.cluster.local:8201"

    listener "tcp" {
      address             = "[::]:8200"
      cluster_address     = "[::]:8201"
      tls_cert_file       = "/openbao/userconfig/openbao-server-tls/tls.crt"
      tls_key_file        = "/openbao/userconfig/openbao-server-tls/tls.key"
      tls_client_ca_file  = "/openbao/userconfig/openbao-server-tls/ca.crt"
    }

    storage "file" {
      path = "/openbao/data"
    }
