apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      containers:
        - name: openbao
          image: ghcr.io/openbao/openbao:2.5.3
          args:
            - bao
            - server
            - -config=/etc/openbao/openbao.hcl
          ports:
            - name: https
              containerPort: 8200
            - name: cluster
              containerPort: 8201
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: https
              scheme: HTTPS
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/openbao
              readOnly: true
            - name: tls
              mountPath: /openbao/userconfig/openbao-server-tls
              readOnly: true
            - name: data
              mountPath: /openbao/data
      volumes:
        - name: config
          configMap:
            name: openbao-config
        - name: tls
          secret:
            secretName: openbao-server-tls
        - name: data
          persistentVolumeClaim:
            claimName: openbao-data
