apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/alexandreia
  - dionysios
  - aristarchos
  - eratosthenes
  - kallimachos
  - eupalinos

components:
  - stoicheia/images
  - stoicheia/version

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: odysseia-common-env
    patch: |-
      - op: replace
        path: /data/EUPALINOS_SERVICE
        value: eupalinos.alexandreia.svc.cluster.local:50060

labels:
  - pairs:
      environment: "hellas"
      variant: "k0s"
      domain: "backend"
    includeSelectors: false
    includeTemplates: true
