apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/odysseia-greek/aristides
    newTag: v0.1.0
  - name: ghcr.io/odysseia-greek/aristophanes
    newTag: v0.8.0
  - name: ghcr.io/odysseia-greek/ktesias
    newTag: v0.1.0
  - name: ghcr.io/odysseia-greek/peisistratos
    newTag: v0.2.1
  - name: ghcr.io/odysseia-greek/periandros
    newTag: v0.2.0
  - name: ghcr.io/odysseia-greek/perikles
    newTag: v0.3.0
  - name: ghcr.io/odysseia-greek/solon
    newTag: v0.3.0
