apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zot
spec:
  serviceName: zot
  replicas: 1
  selector:
    matchLabels:
      app: zot
  template:
    metadata:
      labels:
        app: zot
    spec:
      containers:
        - name: zot
          image: ghcr.io/project-zot/zot-linux-arm64:v2.1.8
          args:
            - serve
            - /etc/zot/config.json
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/zot
              readOnly: true
            - name: auth
              mountPath: /etc/zot/auth
              readOnly: true
            - name: data
              mountPath: /var/lib/zot
      volumes:
        - name: config
          configMap:
            name: zot-config
        - name: auth
          secret:
            secretName: zot-auth
        - name: data
          persistentVolumeClaim:
            claimName: zot-data
