apiVersion: v1
data:
  ARISTARCHOS_SERVICE: aristarchos.alexandreia.svc.cluster.local:50060
kind: ConfigMap
metadata:
  name: xenofon
  namespace: apologia
---
apiVersion: v1
kind: Service
metadata:
  name: xenofon
  namespace: apologia
spec:
  ports:
  - name: grpc
    port: 50060
    targetPort: 50060
  selector:
    app: xenofon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    volumes.odysseia.io/secrets: "true"
  labels:
    app: xenofon
  name: xenofon
  namespace: apologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xenofon
  template:
    metadata:
      annotations:
        odysseia-greek/access: author-based-quiz
        odysseia-greek/role: api
        perikles/accesses: solon
      labels:
        app: xenofon
        release: xenofon
        version: v0.1.3
    spec:
      containers:
      - env:
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/xenofon:v0.1.3
        imagePullPolicy: Always
        name: xenofon
        ports:
        - containerPort: 50060
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 200m
            memory: 64Mi
        volumeMounts: []
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/aristophanes:v0.7.2
        imagePullPolicy: Always
        name: aristophanes
        ports:
        - containerPort: 50052
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 32Mi
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/aristides:v0.0.4
        imagePullPolicy: Always
        name: aristides
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /app/config/vault
          name: vault-server-tls
          readOnly: true
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      initContainers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTIC_ROLE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/role']
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/periandros:v0.1.5
        imagePullPolicy: Always
        name: periandros
        volumeMounts:
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      volumes:
      - name: solon-certs
        secret:
          secretName: solon-tls-certs
      - name: vault-server-tls
        secret:
          secretName: vault-server-tls
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    volumes.odysseia.io/secrets: "true"
  labels:
    app: parmenides-xenofon
  name: parmenides-xenofon
  namespace: apologia
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        odysseia-greek/access: author-based-quiz
        odysseia-greek/role: seeder
        perikles/accesses: solon;aristarchos
      labels:
        app: parmenides-xenofon
        release: xenofon
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        envFrom:
        - configMapRef:
            name: xenofon
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/parmenides:v0.2.1
        imagePullPolicy: Always
        name: parmenides-xenofon
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 200m
            memory: 64Mi
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/aristides:v0.0.4
        imagePullPolicy: Always
        name: aristides
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: 32Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /app/config/vault
          name: vault-server-tls
          readOnly: true
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      initContainers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTIC_ROLE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/role']
        - name: ELASTIC_ACCESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['odysseia-greek/access']
        envFrom:
        - configMapRef:
            name: odysseia-common-env
        image: ghcr.io/odysseia-greek/periandros:v0.1.5
        imagePullPolicy: Always
        name: periandros
        volumeMounts:
        - mountPath: /app/config/solon
          name: solon-certs
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: solon-certs
        secret:
          secretName: solon-tls-certs
      - name: vault-server-tls
        secret:
          secretName: vault-server-tls
