apiVersion: v1
kind: ConfigMap
metadata:
  name: perikles
data:
  VAULT_NAMESPACE: "delphi"
  ELASTIC_NAMESPACE: "agora"
  WATCHED_NAMESPACES: "attike;olympia;makedonia;apologia;alexandreia;ionia"
  CONFIGMAP_NAME: "elastic-roles-and-cnp"
  DASHBOARD_ADDR: ":8080"
