apiVersion: v1
kind: ConfigMap
metadata:
  name: aspasia
data:
  DIONYSIOS_SERVICE: "dionysios.alexandreia.svc.cluster.local:50060"
  ALEXANDROS_GATEWAY: "http://alexandros.makedonia.svc.cluster.local:8080/alexandros/graphql"