apiVersion: apps/v1
kind: Deployment
metadata:
  name: solon
  labels:
    app: solon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solon
  template:
    metadata:
      labels:
        app: solon
        release: solon
      annotations:
        perikles/hostname: "solon"
        perikles/validity: "365"
        solon/namespaces: "attike;olympia;makedonia;apologia;alexandreia;ionia"
    spec:
      serviceAccountName: solon-access-sa
      initContainers:
        - name: peisistratos
          image: ghcr.io/odysseia-greek/peisistratos
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTH_METHOD
              value: token
            - name: VAULT_ROLE
              value: peisistratos
            - name: VAULT_KUBERNETES_TOKEN_PATH
              value: /var/run/secrets/peisistratos-vault/token
          envFrom:
            - configMapRef:
                name: solon
            - configMapRef:
                name: odysseia-common-env
          volumeMounts:
            - name: vault-server-tls
              mountPath: /app/config/vault
              readOnly: true
            - name: peisistratos-vault-auth-token
              mountPath: /var/run/secrets/peisistratos-vault
              readOnly: true
      containers:
        - name: "solon"
          image: ghcr.io/odysseia-greek/solon
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SOLON_MANAGED_NAMESPACES
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['solon/namespaces']
            - name: AUTH_METHOD
              value: kubernetes
            - name: VAULT_ROLE
              value: solon
            - name: VAULT_KUBERNETES_TOKEN_PATH
              value: /var/run/secrets/vault/token
            - name: ELASTIC_SEARCH_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: solon-elastic
            - name: ELASTIC_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: solon-elastic
          envFrom:
            - configMapRef:
                name: solon
          ports:
            - containerPort: 5443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /solon/v1/health
              port: 5443
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /solon/v1/health
              port: 5443
            initialDelaySeconds: 1
            periodSeconds: 20
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /app/config/solon
              name: solon-certs
              readOnly: true
            - mountPath: /app/config/vault
              name: vault-server-tls
              readOnly: true
            - mountPath: /var/run/secrets/vault
              name: vault-auth-token
              readOnly: true
      volumes:
        - name: solon-certs
          secret:
            secretName: solon-tls-certs
        - name: vault-server-tls
          secret:
            secretName: vault-server-tls
        - name: vault-auth-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  audience: vault
                  expirationSeconds: 3600
        - name: peisistratos-vault-auth-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  audience: peisistratos
                  expirationSeconds: 600
