apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FXODPFBbeZOFl0SoRUxBINIK8laeUo6ea0gXipaUOVvvWkoq2rCMJ/WlKqCu2WiAK2gXbnxKxIaf+1KiFoObMyr0ukRo0XZCgsETON/3P7ljsK4SZ0gQY6LOmEyzRqRy8k7TDhPcbeDlXmX+WReWLERZrgrvi7RsDlM+PoPFo+2Y3nZWGfmCVTInSXk8xiqRjKJAE+tEfIGh961a1NVS4zTLbRw4R5Z8tHEHAEw4jQrauHyyryU0JWwJejJjZipvkJJQUjYxgZCQz2ROmhtXvb4yW3LiuwLLqRVzwSQ28Mi21MUTqXrKvQxEsjrc03mxSXp1eld3LQyKb/dgUJU4COWGsZe09zHBgo1zmA==,iv:cFS3t4OQAUld4vE3NSl3t+kfmcoo0sxnO834a9zB7Is=,tag:Ec/e39/ggllbw8jb43RrOA==,type:str]
kind: Secret
metadata:
    name: registry-creds
    namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T08:07:31Z"
    mac: ENC[AES256_GCM,data:tWJlsdpMzkNT97AL3zmEulyJ+ogeiHgri+1WA/w5LLgTMiqFzudgXasuOEYr/LfzgJTHkN7BiiQWKtbU3jmZrUKG0msHj931mPdhmOgkf/b+DaWuWWt3PNe6dHvyvPRToTxN7jYDJzIzrKRqwUclNerJxZsHD2MoFqDjeTOYYi0=,iv:nEDf/XS+AoYfGRc2aRUfs9fB38KR4H19g555zjRWDIE=,tag:1KMbpwxYQZnkbJyLcexIgQ==,type:str]
    pgp:
        - created_at: "2026-06-05T08:07:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/dvIqia++XvAQ//RazcHKmKe5rnBUvhgZ5YjExU814ax39v1yQfmP0bQVFS
            cu2KQFa7/kK3V5y4bxs5dp/CvU5KpmGUQVSPt96bL+IbpEcgEmC2x/LB3OX/JSNc
            HTqLNjcVbuhnRdFoo5GJSyWD+EK33nguaxEA/E3ILRbHffXnEFBYsM19S8Hqi7db
            WLrm1wjKPrHk2ZIPNX8FCRXuunQzoIQe8HfXC1uriMLw/EnNBMoaIZiUzMlXPkBd
            4KEIaELnGE8LyO3O547n2BZQrZOLIrxwNwL7KZWEMY83iFYgDFSZRGL3skfXj2Rv
            FeoShDjz5hAous2vX/DHiyMHNNX0ul/484r/BWJt9b3m13hH+mvnDV/mUrws9qwu
            vnTcFZS56D23p3Hg0DKIImYyZQVM09E4CAuBdp0qcx1ixKjV8YoF3O8PgWSHGDHo
            Otb/e1VT7RgP8WF7iCkE55Aul87b59riOht/KmoG2MaufjuUouizVpT3gu4NdMx6
            S7ItRXjWkKyAJT9uySBeKehub4qNz07jptVwOhkxlxpzOTOVVLMprReX36lXvJnB
            kZsd7TcCXlFo/I3/DpqGYXoAxL4eQ/kz2JQkSb0eJSB43gwBDMHTzHVe6IRoVrgu
            3dDmjAOusrMZyj0g0nhQWFxgfBGCFlZee1qI3Auh+CxH585RmQUy/Jd4kTf6nNHU
            ZgEJAhBob6CUjAqLXakzAxGWh2LAFEH5ZDuQMQo3TtYg8bktuIu9q8F86PfPDMeo
            YlJia8gtGEVR+cjgV3VniD18ODqeJXYwHxw3tRR4R98c5NEFAQhOvQZRB5Pa0/ro
            /6NMhJgyvg==
            =dKmY
            -----END PGP MESSAGE-----
          fp: 3C8B5BB6281C34C5E80C473086FCFB28CF0EC482
    version: 3.13.1
