apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8G8aJabek4qAZm5+eHKxQqXRju7j0SScY0Sh4xzZTw6L3v2JdK1EtVZjHhzdXtqphbo031X59fxRBz5d19BzR21ncdyXQu5k/lJcEYu44quoDN8vs2Tc0bvv0yaY5bVet7O3MSXkJHLT5GrmqpdF0y1qFULvH2WazGr6w5JHBO7Aj8rnC/4FrcygTrUacQ86FYYpuOs8M0wEEh6gCHRe4o5Fcpq+mzkSXlJlE+LA11cY9H68gKHUg6C+g0xnRgZ5jZsfqXNpNcMf4Cfd/yVxzCJxvXIrGdEcxBwcKGPeHEUhJOTz,iv:+4smqrO0wiVmlStyLskYA4nk+6xUMBxW4pbCV8ISy7k=,tag:0vXpma11/hxrvyXtBdEdPA==,type:str]
kind: Secret
metadata:
    name: registry-creds
    namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2026-05-03T14:15:56Z"
    mac: ENC[AES256_GCM,data:hBdLyB5KTWozs2Q8z727vWryf3WP94cRHfe1CD/WNRwD7pjMpkGa7bGdVoRzf38z8F68adeLqWeBqgRTGYhh0cgGJEvJM5jm1Z+mxIbtAhsxfsTRHG8ZoxD9hFn/CRuqnROf4K1+QCJGknZKST2ChCMuEHuVp0BK+GbQ5DbvyAQ=,iv:3UZs6kIFjXlMdZ0RFLeZNN2NSF6qrmGrHcPptizj14k=,tag:p4+kpVlAGzsWrS4aVB8yQg==,type:str]
    pgp:
        - created_at: "2026-05-03T14:15:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/dvIqia++XvAQ/9EwRNxMEisFGoCBCzCcj7n4NU4qEl1oggfKGBvBBfgCFG
            5aijOOwomi43BvYemalu3h1GU3qat2YF9yQJtNXMDIs3y5xQdL9UurP5VzyPKPO5
            qXjV/6Ykj4sjsTDi1euFtiDb2oP18TDMlThQkhsGzKKuqALCR3OsRQXgRH7Eujc1
            NwdJOV/U9K+s8qyVhK8ZWB48x/p8ny0Xykpg3kMqT371w+Jq3ysrLmijHLoF/t46
            BPDDKTT69OjoaCV1dNTjhRZ0CotM6xKAtRrBy9D1PtLgjlGJjX09PmjLeiE1WqEn
            26a88puI5Gs4zKqrzpEYdjSdg10L3tjooLjTKjzbl0WVs3cs/sBuG4IeBz8uaRRq
            iTYsTIwzgXzFrH4dLKH/bRgmcfEq/+yNqSiwElZ0pj2zz/uoL/TXyTGrpJUixhxh
            YuF7fOr/eeIpFwhIEN+WHJBHydws45NZmDz0c8w5TvxblsckaepwCzx+5nYVQWDU
            yKi4CrfBjZQKK7LWTQGU2Mdf/9ciVJyaJcaSpfYS5IRgi1M3XMyIkMPnSxKPamFZ
            woIe3t36nPeokYJcLQRpDd5jPydM0/I7WTV/RSzpnOk7GnaOSbDmpj9tZy1tNtrz
            7ewvJHiZmb+yKWL/7qyhV30ghLxHUMQdj2//deCsdAD8MZ6TVkn/SMH56kQ/ThfU
            aAEJAhBSQJyazPJ5L0CtPblPyZ0tnI7pcnFQm+dbWo6O6uIDG80BmoWncFMgdwie
            6zzqAVm7QsRuglCwEPNAgqxPRWYcFOH+1wII0jkvD+BJdRdUl4/gXRmymXzkRDOd
            KXXyINlMhX9n
            =AX30
            -----END PGP MESSAGE-----
          fp: 3C8B5BB6281C34C5E80C473086FCFB28CF0EC482
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
