apiVersion: v1
kind: Node
metadata:
  name: sparta-hellas
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: disabled
  labels:
    cilium.io/envoy-capable: "true"
    odysseia-greek/topolvm: pyxis
    odysseia-greek/ingress-role: primary
---
apiVersion: v1
kind: Node
metadata:
  name: athenai-hellas
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: disabled
  labels:
    cilium.io/envoy-capable: "true"
    odysseia-greek/topolvm: pyxis
    odysseia-greek/elastic-role: all
    odysseia-greek/elastic-memory-tier: high
---
apiVersion: v1
kind: Node
metadata:
  name: thebai-hellas
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: disabled
  labels:
    cilium.io/envoy-capable: "true"
    odysseia-greek/topolvm: pyxis
    odysseia-greek/elastic-memory-tier: standard
