apiVersion: apps/v1
kind: Deployment
metadata:
  name: diodoros
  labels:
    app: diodoros
  annotations:
    volumes.odysseia.io/secrets: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diodoros
  template:
    metadata:
      labels:
        app: diodoros
        release: diodoros
      annotations:
        odysseia-greek/role: api
        odysseia-greek/access: text
        perikles/accesses: "solon"
    spec:
      initContainers:
        - name: herakleitos
          image: ghcr.io/odysseia-greek/herakleitos
          imagePullPolicy: Always
          env:
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: odysseia-common-env
          volumeMounts:
            - name: solon-certs
              mountPath: /app/config/solon
              readOnly: true
      containers:
        - name: diodoros
          image: ghcr.io/odysseia-greek/diodoros
          imagePullPolicy: Always
          env:
            - name: PORT
              value: ":50060"
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom: []
          volumeMounts: []
          ports:
            - containerPort: 50060
      volumes: []
