apiVersion: v1
kind: Node
metadata:
  name: lima-k0s-byzantion
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: disabled
  labels:
    cilium.io/envoy-capable: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: lima-trapezous
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: disabled
  labels:
    cilium.io/envoy-capable: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: lima-nikaia
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: disabled
  labels:
    cilium.io/envoy-capable: "true"
