apiVersion: apps/v1
kind: Deployment
metadata:
  name: herodotos
  labels:
    app: herodotos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herodotos
  template:
    metadata:
      labels:
        app: herodotos
        release: herodotos
      annotations:
        perikles/accesses: "thoukydides;diodoros"
    spec:
      containers:
        - name: herodotos
          image: ghcr.io/odysseia-greek/herodotos
          imagePullPolicy: Always
          env: []
          envFrom:
            - configMapRef:
                name: herodotos
          ports:
            - name: graphql
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
